### ISSUE TITLE
Create the FAQ Page 

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#10]
Create the FAQ page. For this  you have to  create a accordion similar to [mongoDB](https://www.mongodb.com/cloud/atlas/faq)  faq page and you can use placeholder data (Lorem ipsum...)  for now. 

You have to create a component of accordion in [components > elements ](https://github.com/opencodeiiita/SaveMyForm-Frontend/tree/main/components/elements)
- Create a folder in elements folder
-  Create a file index.js in that folder and work in that
-  Then import that component in [faq](https://github.com/opencodeiiita/SaveMyForm-Frontend/tree/main/pages/faq) page in pages folder and place there

**Comment by vishalola** [comment]
claim

**Comment by Manas2403** [comment]
Congratulations!. You have 48 hours for this task.
Happy Contributing!!
