### ISSUE TITLE
I'll GET You

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#102]
For this task you have to fetch the details of the user in dashboard page (https://github.com/opencodeiiita/SaveMyForm-Frontend/blob/main/pages/dashboard/index.js)

Steps to follow:
- Read the documentation [here](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/API_Endpoints.md).
- Write a function to fetch the user details on the dashboard page and log the response.

For any doubts, ask on discord.

Use the functions provided in API folder in `components/utils`.

**Comment by vishalola** [comment]
claim

**Comment by Manas2403** [comment]
Assigned to @vishalola

**Comment by Manas2403** [comment]
updates @vishalola ?

**Comment by vishalola** [comment]
@Manas2403 Ill start working on it tonight. Took a day off yesterday

**Comment by Manas2403** [comment]
updates @vishalola ?

**Comment by sushantk1274** [comment]
claim

**Comment by Manas2403** [comment]
updates @sushantk1274 ?

**Comment by sushantk1274** [comment]
Samajhne ki koshish kar raha

**Comment by Manas2403** [comment]
Giving you time till tomorrow, after that I will reassign. 

If you have any doubts,ask on discord.

**Comment by Manas2403** [comment]
updates @sushantk1274  ?

**Comment by sushantk1274** [comment]
Bro I am traveling so net strength is poor...may you give me 1 more day

**Comment by Manas2403** [comment]
TIme till today noon. After that i will reassign. @sushantk1274

**Comment by SanyamAgrawal07** [comment]
Claim
