### ISSUE TITLE
UPDATE

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#103]
For this task you have to write a function to update the password of the user in the [settings](https://github.com/opencodeiiita/SaveMyForm-Frontend/tree/main/pages/settings) page.

Steps to follow:
- Read the API documentation (https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/API_Endpoints.md).
- You have to check that New password should be of length >6 .
- Check that new password and confirm password are same.
- Send the post request to backend and log the result.
- check that no input field should be empty.
-  If the user clicks on the cancel button clear all the input fields.

Use the functions in API folder defined in `components/utils/` .

For any doubts ask on discord.

**Comment by MistyRavager** [comment]
Claim

**Comment by Manas2403** [comment]
Assigned to @MistyRavager
