### ISSUE TITLE
Google OAuth

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#108]
For this task, you have to implement Google OAuth on signup and signin page. 

Steps to follow:
- Read [Documentation](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/API_Endpoints.md#authgoogle)
-  Create a component GoogleOAuth in `components/element/`.
-  Place the component in signup and signin page next to submit button.
- Create a button in the component. Button design is given below.
- Fetch google auth url from backend.
- Open the url in same tab (find a way to do it) 
-  After successful authorization, rest of the process will continue in `signin/oauth` .
- In the `signin/oauth` page, in the query parameter, you will get a code you will have to send the code to the backend as a POST request.
- On successful response from backend redirect to dashboard. 

![image](https://user-images.githubusercontent.com/90680751/210167328-a654a4ef-a084-4dc8-9a09-ea4ac2feec7c.png)

**Comment by Shubhankit-Pandey** [comment]
Claim

**Comment by Manas2403** [comment]
Assigned to @Shubhankit-Pandey

**Comment by akshayw1** [comment]
claim
