### ISSUE TITLE
New Form 

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#109]
For this task, you have to create a page for new form. You have to write your code in this [file](https://github.com/opencodeiiita/SaveMyForm-Frontend/tree/main/pages/dashboard/project/%5Bid%5D/newform).

You can use components also and then place them in the file.

You can take reference from this [page](https://github.com/opencodeiiita/SaveMyForm-Frontend/tree/main/pages/dashboard/project/newproject). (`localhost:3000/dashboard/project/newproject`)

Required fields 
- Form name (type text)
-  reCAPTCHA Support ( type checkbox)

You can see your changes on `localhost:3000/dashboard/project/id/newform`

![image](https://user-images.githubusercontent.com/90680751/210169270-dc77552f-2e15-4c9a-bfa0-4f0e73b51692.png)

**Comment by Kali-Decoder** [comment]
Claim
