### ISSUE TITLE
Form Field

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#112]
For this task, you have to create a component in `components/element`. The sample design of the component is in figma file under heading New Form . No need to make it exact same.
 
Steps to follow:
- The first column is Name which will be a text input.
-  The second column is type of input . It should be dropdown listing all possible html input types. List of all possible html input types (https://www.w3schools.com/html/html_form_input_types.asp).
-  The third column is isRequired boolean which is of type checkbox.
-  Import your component [here](https://github.com/opencodeiiita/SaveMyForm-Frontend/tree/main/pages/dashboard/project/%5Bid%5D/newform). You can view your changes on `localhost:3000/dashboard/project/2/newform`.

You can use antd components to implement dropdown, checkbox etc.
For any doubts ask on discord.

**Comment by vishalola** [comment]
claim

**Comment by GammaMicrowave** [comment]
claim

**Comment by Manas2403** [comment]
@vishalola  issue already assigned

**Comment by Manas2403** [comment]
Assigned to @GammaMicrowave
