### ISSUE TITLE
Code 404

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#116]
For this task, you have to code 404 error page for the website . Design is in the figma file provided. Write your code [here](https://github.com/opencodeiiita/SaveMyForm-Frontend/tree/main/pages/404).

The page should be responsive.

For mobile design, place the vector on top then text.
Go to `localhost:3000/404` to view your changes.

For any doubts, ask on discord.

**Comment by Kali-Decoder** [comment]
Claim

**Comment by Akash190iiit** [comment]
Claim

**Comment by Manas2403** [comment]
Assigned to @Akash190iiit

**Comment by Manas2403** [comment]
@Kali-Decoder  you have an issue assigned to you

**Comment by Kali-Decoder** [comment]
But i raised pr @Manas2403

**Comment by Manas2403** [comment]
I have requested changes in that.

**Comment by Manas2403** [comment]
updates @Akash190iiit

**Comment by Manas2403** [comment]
Assigned to @Kali-Decoder

**Comment by Manas2403** [comment]
@Kali-Decoder  you have 3 issues already assigned so need to unassign this one

**Comment by Kali-Decoder** [comment]
Okk

**Comment by Kali-Decoder** [comment]
But i have code ready for this can i raised pr

**Comment by GammaMicrowave** [comment]
claim

**Comment by Manas2403** [comment]
Assigned to @GammaMicrowave
