### ISSUE TITLE
POST Project 

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#119]
For this task you have to write a function which sends a POST request to backend to create a new project.

Steps to follow:
- Read the [documentation](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/API_Endpoints.md#project-endpoints).
- Use the post method defined in `components/utils/API`.
- Write your code [here](https://github.com/opencodeiiita/SaveMyForm-Frontend/tree/main/pages/dashboard/project/newproject).

Go to `localhost:3000/dashboard/project/newproject` to test your function.

**Comment by MistyRavager** [comment]
Claim

**Comment by Manas2403** [comment]
Assigned to @MistyRavager
