### ISSUE TITLE
NewForm Fields

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#123]
For this task, you have to implement FormField Input in [newform](https://www.savemyform.tk/dashboard/project/2/newform) page of the website.

Steps to follow:
- FormField component is already made in Newform in `componenets/element`.
- In newform page you have to import this component .
- not more than 10 fields is required
- only one file input is allowed

**Comment by GammaMicrowave** [comment]
Clem

**Comment by Manas2403** [comment]
Assigned to @GammaMicrowave

**Comment by harshit995** [comment]
want to contribute
