### ISSUE TITLE
DELETE Project

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#124]
Add a delete button on [this](localhost:3000/dashboard/project) page below settings button.

On click of button add a modal window, which asks for the password of the user. You can use`antd` modal for easy implementation.

Go to `localhost:3000/dashboard/project` to view your changes.

**Comment by GammaMicrowave** [comment]
Claim

**Comment by Manas2403** [comment]
Assigned to @GammaMicrowave
