### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#125]
Steps to follow

- Create a folder name documentation on the outermost level. 
- In the folder initialize the documentation project using the link below provided.

Follow the steps described in https://nextra.site/docs/docs-theme/start#start-as-new-project .
Use npm

**Comment by SanyamAgrawal07** [comment]
Claim

**Comment by Manas2403** [comment]
Assigned to @SanyamAgrawal07
