### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#131]
There is a small change to be done on home page. I have attached the image below, The left vector should be properly aligned according to the design in figma file. Make sure no other  thing gets affected by your changes. 
![image](https://user-images.githubusercontent.com/90680751/211142413-8cd3ca00-f90d-4cfc-a00b-c547964382ad.png)

**Comment by TheDivineAurora** [comment]
Claim

**Comment by Manas2403** [comment]
Assigned to @TheDivineAurora

**Comment by harshit995** [comment]
want to contribute

**Comment by Manas2403** [comment]
Updates @TheDivineAurora

**Comment by TheDivineAurora** [comment]
7pm sir
