### ISSUE TITLE
JSON Schema

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#135]
Convert the array of input fields present in the [newform](https://github.com/opencodeiiita/SaveMyForm-Frontend/tree/main/pages/dashboard/project/%5Bid%5D/newform) file into a [JSON Schema](https://json-schema.org/understanding-json-schema/) with every input field name as a property of JSON Schema. All the required input fields should be marked as required in JSON Schema.
I advise you to read the documentation of [JSON Schema](https://json-schema.org/understanding-json-schema/) first before starting.

For any doubts, ask on discord.
See you changes on `localhost:3000/dashboard/project/2/newform`.

**Comment by Kali-Decoder** [comment]
Claim

**Comment by Manas2403** [comment]
Assigned to @Kali-Decoder

**Comment by Manas2403** [comment]
Updates @Kali-Decoder  ?

**Comment by Kali-Decoder** [comment]
Almost done bhaiya

**Comment by GammaMicrowave** [comment]
claim

**Comment by Manas2403** [comment]
Assigned to @GammaMicrowave
