### ISSUE TITLE
Homepage BUG

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Frontend#137]
There should be no spacing between the two vectors shown in image. Fix that bug.
For any doubts ask on discord.
![image](https://user-images.githubusercontent.com/76420937/211213746-94cf1442-fc36-467d-b12f-17ed2d7884a1.png)

**Comment by Sushi1274** [comment]
claim

**Comment by Manas2403** [comment]
Assigned to @Sushi1274

**Comment by Rishav1707** [comment]
@Manas2403 Please accept my PR. It will never happen next time.

**Comment by Manas2403** [comment]
updates @Sushi1274 ?

**Comment by antsharma** [comment]
Claim

**Comment by Manas2403** [comment]
Assigned to @antsharma

**Comment by Rishav1707** [comment]
I have solved this issue but you haven't merged. I have also requested you but you can't...

**Comment by Rishav1707** [comment]
> Assigned to @antsharma

And you have also assigned this issue to someone, that's not fair enough.

**Comment by Rishav1707** [comment]
Claim @Manas2403
