### ISSUE TITLE
Fix position of circle  on home page

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#164]
![image](https://github.com/opencodeiiita/SaveMyForm-Frontend/assets/90680751/f8b82f38-c525-4091-ac21-4a2414d3ba2e)

The circle in above image overlaps another circle, we want you to fix its position . See the figma file for reference.
You can find the code in /components/sections/feature.js

**Comment by chandra1899** [comment]
can you assign this issue to me ....

**Comment by chandra1899** [comment]
sir , how can i contact you to discuss about the issue ?

**Comment by Manas2403** [comment]
You can join the discord server https://discord.gg/Wy8kEfsc 
and ask your doubts in savemyform-frontend channel

**Comment by Vishesh-Vijay** [comment]
claim

**Comment by chandra1899** [comment]
@Manas2403 

> You can join the discord server https://discord.gg/Wy8kEfsc and ask your doubts in savemyform-frontend channel @chandra1899

it is showing "unable to accept invitation"
