### ISSUE TITLE
Form Dashboard

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#165]
Create the form dashboard page. Make sure to make a reusable form component that accepts the following props:
formName, createdAt,submissions.
Make the component in the /components/element and the page code in /pages/dashboard/project/[id]/index.js [file](https://github.com/opencodeiiita/SaveMyForm-Frontend/blob/main/pages/dashboard/project/%5Bid%5D/index.js)

- No need to make the navbar and footer for now.

- You can use antd for importing ui components.
-  You can refer the figma file 
-  The page should be completely responsive.

![image](https://github.com/opencodeiiita/SaveMyForm-Frontend/assets/90680751/07007479-e7af-4d7e-ab8a-589933070d64)

**Comment by JahnaviGadde** [comment]
claim

**Comment by Vishesh-Vijay** [comment]
Claim
