### ISSUE TITLE
Create the dashboard page 

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#17]
Create the dashboard page for the project . Go to [`pages > dashboard > index.js`](https://github.com/opencodeiiita/SaveMyForm-Frontend/blob/main/pages/dashboard/index.js) and do the required changes . You can make different components and sections to make the page or do the complete work in the single file. 

---

Go to [localhost:3000/dashboard](http://localhost:3000/dashboard) to see your changes. 

Design of the page is in the figma link provided in the Readme under the heading Client Section. 

You can ignore the navbar for now and place temporary data in all the fields present .

![Client Section](https://user-images.githubusercontent.com/90680751/208295291-65937ffd-155e-4cf8-8e09-9c1996093c38.png)

**Comment by GammaMicrowave** [comment]
Claim

**Comment by Manas2403** [comment]
Assigned to @GammaMicrowave

**Comment by Kali-Decoder** [comment]
Claim

**Comment by Manas2403** [comment]
@Kali-Decoder issue is already claimed.  More issues will be coming up. Stay tuned!
