### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#174]
Code the footer .
Create  a component in /components/elements.
Place it in dashboard2 page.
You can take reference from the figma file.
![image](https://github.com/opencodeiiita/SaveMyForm-Frontend/assets/90680751/c2d0fb0e-89a1-4665-b37e-7cb9e57d6ab7)

**Comment by Vishesh-Vijay** [comment]
Claim
