### ISSUE TITLE
Create the Login Page

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#23]
Create the login page, just place, and style the components. Make the page same as of signup page. You can refer the code in signup page.

Required input fields:
- Email
-  Password

and a submit button.

Use [tailwind](https://tailwindcss.com/docs/installation) for styling, you can also use [antd components](https://ant.design/components/overview/) on this page.

---

You will have to write the code in this file: [pages > signin > index.js](https://github.com/opencodeiiita/SaveMyForm-Frontend/blob/main/pages/signin/index.js)

**Comment by vishalola** [comment]
claim

**Comment by Manas2403** [comment]
Assigned to @vishalola

**Comment by Manas2403** [comment]
PR ? @vishalola

**Comment by Kali-Decoder** [comment]
claim
