### ISSUE TITLE
Update or create new  form for new project

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#28]
The page should look similar to [this](https://www.google.com/recaptcha/admin/create) but make sure you follow the color theme given in the design file in readme. 
 You should write code [here](https://github.com/opencodeiiita/SaveMyForm-Frontend/tree/main/pages/dashboard/project/newproject) or make components and import here as you wish.
Go to [localhost:3000/dashboard/project/newproject](http://ocalhost:3000/dashboard/project/newproject) to see your changes.

The required fields in the form are:
- **Project Name**: Text
- **Collaborators**: For this input field is of type email and there will be a ➕  icon to add more collaborators. See the working of owners field in above given link and implement the same thing for our form.
- **Domains**: Implement the same way as in the domain field of the above given link.

A **checkbox** field which asks for whether the project has reCAPTCHA support or not. If it is checked show two input fields:
- reCAPTCHA key
- reCAPTCHA secret

if it is unchecked don't show the input fields.

A **Cancel button** to clear all the input fields when clicked and a **submit button** to submit the form which will be implemented later for now just create the  submit button and cancel button should be working.

Some code is  already there in the file . Either update that or you can create from scratch.  Page should be completely responsive
---

If you have any doubts do ask on discord.

**Comment by vishalola** [comment]
claim

**Comment by Shubhankit-Pandey** [comment]
claim

**Comment by Manas2403** [comment]
@vishalola  u already have an issue assigned in the repository and you can work on only one issue at a time in the repository.

**Comment by vishalola** [comment]
I'm done with that one. May I make a PR for that one as soon as I reach home? (15 mins)

**Comment by Manas2403** [comment]
Sure

**Comment by Manas2403** [comment]
@vedant-z  u already have 3 issues assigned to you. No more for now.

**Comment by Aman1143** [comment]
claim

**Comment by Manas2403** [comment]
Assigned to @Aman1143 . You have 48hrs to complete the task.

**Comment by Kali-Decoder** [comment]
claim

**Comment by Manas2403** [comment]
Issue is already been assigned to @Aman1143 .

**Comment by Manas2403** [comment]
@Aman1143  updates ?

**Comment by Aman1143** [comment]
Yes I am working

**Comment by Manas2403** [comment]
@Aman1143  can you upload a screenshot of the current progress so that i can tell you if we need some changes.

**Comment by vishalola** [comment]
@Manas2403 i guess the allotted time is over. 
I wish to claim this if Aman fails to deliver

**Comment by Manas2403** [comment]
@Aman1143  you have time till midnight. After that it will be open for claim again.

**Comment by Manas2403** [comment]
@vishalola  if Aman fails to deliver. Issue will be opened again and  the person claiming first again will get the issue.

**Comment by GammaMicrowave** [comment]
claim

**Comment by vishalola** [comment]
gammmamaaaaasdabsdbajkbdkjawbd

**Comment by Manas2403** [comment]
Assigned to @GammaMicrowave

**Comment by Manas2403** [comment]
Finally closed !! Great work @GammaMicrowave
