### ISSUE TITLE
Create the Client Settings Page

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#35]
Create the client settings page for the project . Go to [`pages > settings> index.js`](https://github.com/opencodeiiita/SaveMyForm-Frontend/tree/main/pages/settings/index.js) and do the required changes . You can make different components and sections to make the page or do the complete work in the single file. 

---

Go to [localhost:3000/settings](http://localhost:3000/settings) to see your changes. 

Design of the page is in the figma link provided in the Readme under the heading Client Settings. 

You can ignore the navbar for now and place temporary data in all the fields present .
Make sure the page is responsive.

![Client Settings](https://user-images.githubusercontent.com/90680751/208507684-810e6726-7a90-4f76-bd85-16c2f5e6347c.png)

**Comment by GammaMicrowave** [comment]
claim

**Comment by hargunkaur286** [comment]
claim

**Comment by Manas2403** [comment]
Assigned to @GammaMicrowave
