### ISSUE TITLE
DiceBear Avatars

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#36]
You have to generate a random avatar and show it in place of the filled div left of name and email.
![avatar](https://user-images.githubusercontent.com/90680751/208510017-3bebb6fa-ecf7-43bb-9f65-e87be116c868.png)

For this follow the steps mentioned in the [docs](https://avatars.dicebear.com/styles/avataaars)
- Install the npm package for the task.
- Create an element in the elements folder which is in components folder (**mandatory for this task**) then import it in dashboard page and use.

If you have any doubts,  feel free to ask on discord.

**Comment by hargunkaur286** [comment]
claim

**Comment by Manas2403** [comment]
updates @hargunkaur286  ?

**Comment by hargunkaur286** [comment]
Still working on it. Will make the PR soon
