### ISSUE TITLE
Think of FAQs for the project SaveMyForm

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#37]
**OPEN FOR ALL** Issue
Think of atleast 2 FAQs for the project SaveMyForm.  Refer this [document](https://docs.google.com/document/d/1F6VB2uJpWLh0WL9Uy5BrzsT0NAzwHauUbkJ01vc-av8/edit?usp=sharing) to know about the project and think accordingly.

You can refer other sites to get to know how they frame their FAQ section.

Create a file in faqs folder with file name as < github-username >.json. A sample file is given in the folder refer that and add accordingly.

Files with less than 2 faqs will not be merged and you need to  think of unique faqs don't copy from other pull requests.

**Comment by frikinomad** [comment]
Claim

**Comment by Manas2403** [comment]
It is an open for all issu. Just create a PR when ready.

**Comment by frikinomad** [comment]
my bad, thanks
