### ISSUE TITLE
Find a  library or npm package for creating documentation page

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#40]
We have to create documentation for our project SaveMyForm. You might have seen other documentation pages of different pages which have a sidebar.  So we want to create a similar kind of page. So find a npm package or some library  which helps in creating documentation page UI. 
Create a file in **documentation** folder with file name as < github-username >.json. A sample file is given in the folder refer that and add accordingly.
You can add as many packages as you want with a minimum requirement of 2.
For any doubts, feel free to ask on discord.
The issue is **OPEN FOR ALL**.

**Comment by iamatifmoin** [comment]
Claim

**Comment by Manas2403** [comment]
No need to claim!
