### ISSUE TITLE
Create the Project Dashboard Page

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#41]
Create the dashboard page for the project . Go to [`pages > dashboard > project > index.js`](https://github.com/opencodeiiita/SaveMyForm-Frontend/blob/main/pages/dashboard/project/index.js) and do the required changes . You can make different components and sections to make the page or do the complete work in the single file. 

---

Go to [localhost:3000/dashboard/project](http://localhost:3000/dashboard/project) to see your changes. 

Design of the page is in the figma link provided in the Readme under the heading Project Dashboard. 

You can ignore the navbar for now and place temporary data in all the fields present .

Take reference from dashboard page which is same as of this page so you will get a  lot of help from there.
---
![Project Dashboard](https://user-images.githubusercontent.com/90680751/208740804-c6062dac-f7b7-4336-a95d-161b5cc9cc2b.png)

**Comment by GammaMicrowave** [comment]
claim

**Comment by Im-Madhur-Gupta** [comment]
Claim

**Comment by Shubhankit-Pandey** [comment]
claim

**Comment by Manas2403** [comment]
Assigned to @GammaMicrowave

**Comment by Manas2403** [comment]
@Im-Madhur-Gupta  @Shubhankit-Pandey  late by just seconds . Better luck next time!
