### ISSUE TITLE
Add Vector on Signin and Signup Page

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#44]
For this task use [this](https://github.com/opencodeiiita/SaveMyForm-Frontend/blob/main/assets/images/illustrations/signin.png) vector and place it on signin and signup page in place of the left div which is having a background  colorright now. 

The vector is already downloaded in assets folder no need to download it again.

On small screens (<576px) no need to show the vector just hide that div.

Make sure you place the vector on both signin and signup pages.

**Comment by GammaMicrowave** [comment]
claim

**Comment by Shubhankit-Pandey** [comment]
Claim

**Comment by Manas2403** [comment]
You already have an issue assigned to you @GammaMicrowave  in this repo.

**Comment by Manas2403** [comment]
Assigned to @Shubhankit-Pandey

**Comment by GammaMicrowave** [comment]
aight

**Comment by Manas2403** [comment]
@Shubhankit-Pandey  udpates ? Not a big task ig . Try to close it asap

**Comment by Manas2403** [comment]
Good work @Shubhankit-Pandey
