### ISSUE TITLE
Implement Signup functionality 

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#65]
Steps to implement:
- Take the user input from the form 
-  Check that password length should be greater than 6.
- Request structure can be found [here](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/API_Endpoints.md#auth-endpoints)
- For successful response from the server, you will get a `secret` in the response. Store that in localStorage with key name secret.
- For each response show a message(antd component) whether signup was  successful or not.
- In the recaptcha_token field of signup POST request, you can send temporary string for now.
---
The helper functions for sending requests are present in the `components/utils/API` folder and for localStorage functions are in `components/utils/LocalStorage` folder. Use these function only to send request.

--- 
Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible.

**All the Best!!**

**Comment by TheDivineAurora** [comment]
claim

**Comment by Manas2403** [comment]
Assigned to @TheDivineAurora

**Comment by Manas2403** [comment]
Any blockers @TheDivineAurora  ?

**Comment by TheDivineAurora** [comment]
Give me time !

**Comment by Manas2403** [comment]
Giving you time till 2 am @TheDivineAurora

**Comment by TheDivineAurora** [comment]
Ok

**Comment by Manas2403** [comment]
Good work @TheDivineAurora
