### ISSUE TITLE
Implement Beta Alert Banner on website

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#69]
For this task, implement a banner as shown in [design ](https://www.figma.com/file/2KnOYD17aRMhXw8qhuuEKu/Theme?node-id=0%3A1&t=E6ASv1ZSvHk2bERS-1)  file.

Follow the steps for better implementation:
-  Create a Banner component in `component/elements/` and export it
-  Implement a cross button to show banner or not as shown in design.
-  banner should be responsive.
-  We want to show the banner on every page but without importing it again and again on every page. Find a way so that only one import statement works. Try to find the correct way.

---
If you are not able to find the solution you can ask your doubts on discord.

**Comment by hargunkaur286** [comment]
claim

**Comment by GammaMicrowave** [comment]
claim

**Comment by GammaMicrowave** [comment]
claim

**Comment by Manas2403** [comment]
Assigned to @hargunkaur286

**Comment by antsharma** [comment]
claim

**Comment by Manas2403** [comment]
Any doubts @hargunkaur286  ?
