### ISSUE TITLE
Design or find a vector for login/signup page

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#7]
OPEN TO ALL.
NO need to claim this issue.
---
We will be displaying a vector on the login/signup page. We are taking reference of the login/signup page from the websites [greenhouse.com](https://app.greenhouse.io/users/sign_in) and [mongodb.com](https://account.mongodb.com/account/login). Make sure to pick a vector according to the theme of the project.
Keep in mind, if you are picking a vector from online websites, there should be no copyright issues.

Enter your github account and attach the vector link in the [designs.json](https://github.com/opencodeiiita/SaveMyForm-Frontend/blob/main/designs.json) file, in the respective field.

**Comment by vedant-z** [comment]
@Manas2403 Vector in case of MongoDB is this right?

![IMG_20221218_101838.jpg](https://user-images.githubusercontent.com/93431609/208282008-f220473a-fa3f-4ad0-a565-f9169245992a.jpg)

**Comment by Manas2403** [comment]
![image](https://user-images.githubusercontent.com/90680751/208286888-11261fc0-0058-4389-bdba-649cf78ba05c.png)

Basically what we want is similar to this as you can see there is a vector on left side so we also want the same but vector should depict something about our idea of SaveMyForm or vector related to login/signup. We do not want a logo of any organization.
