### ISSUE TITLE
Create the Navbar of the website 

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#70]
Create the navbar for the website. Design is in the figma link provided in the README.
Steps to follow:
- Create a navbar component in `components/elements/`
- Logo is in the navbar design. Export it from there as `svg` and create a folder  `logos` in `assets/images` .
- Import the navbar component in _app.js.

**Comment by Aman1143** [comment]
claim

**Comment by Aman1143** [comment]
it's design So I am out Sorry

**Comment by BuddyLongLegs** [comment]
P.S.: Umm, design is provided, you have to implement.

**Comment by antsharma** [comment]
claim

**Comment by Manas2403** [comment]
Assigned to @antsharma

**Comment by rajiss-ctrl** [comment]
Hi,
can I contribute/ handle the navbar?

**Comment by Manas2403** [comment]
@rajiss-ctrl  whoever first claims the issue is assigned that task.

**Comment by Manas2403** [comment]
@antsharma  any blockers ?

**Comment by Kali-Decoder** [comment]
Can i raised PR for this i am ready with this issue

**Comment by Manas2403** [comment]
No, you can't as issue is assigned to someone else.

**Comment by Manas2403** [comment]
@antsharma  giving you time till today noon,  after that it will be reassigned.

**Comment by Kali-Decoder** [comment]
claim

**Comment by TheDivineAurora** [comment]
claim

**Comment by Manas2403** [comment]
Assigned to @TheDivineAurora

**Comment by GammaMicrowave** [comment]
dedo plej

**Comment by GammaMicrowave** [comment]
kya bigada hai mene tumhara

**Comment by Kali-Decoder** [comment]
Bt h bhai 🥲🥲 queue ke hissab se dena chahiye

**Comment by Manas2403** [comment]
@Kali-Decoder  whenever issue is open for reclaim, you have to write claim again. There is no such rule of queue and all

**Comment by Manas2403** [comment]
@GammaMicrowave you have three issues already.

**Comment by Manas2403** [comment]
Assigned to @Kali-Decoder

**Comment by Manas2403** [comment]
@Kali-Decoder  updates ?

**Comment by TheDivineAurora** [comment]
claim

**Comment by GammaMicrowave** [comment]
F

**Comment by Kali-Decoder** [comment]
Claim

**Comment by abhinavs1920** [comment]
Claim

**Comment by TheDivineAurora** [comment]
gamam sir go ahead

**Comment by Manas2403** [comment]
Assigned to @abhinavs1920

**Comment by Manas2403** [comment]
@abhinavs1920  you have 48hrs to complete the task. Best of luck!

**Comment by abhinavs1920** [comment]
Please sir reassign navbar issue to someone else , I am having some issues creating it

**Comment by GammaMicrowave** [comment]
clem

**Comment by Manas2403** [comment]
Assigned to @GammaMicrowave

**Comment by Kali-Decoder** [comment]
claim
