### ISSUE TITLE
Code the Hero 

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#71]
For this task, you have to code the hero section of the website. Design is provided in the figma link provided in README under heading HomeScreen Header.

Steps to follow:
- Create a section named HeroSection in `components/sections/` and work there.
- Import the section in  `pages/home` .
- You can see your changes  on `http://localhost:3000/home.

---
Make the sure hero section is responsive. No need to work on the  navbar.

**Comment by GammaMicrowave** [comment]
claim

**Comment by Manas2403** [comment]
You already have 3 issues assigned to you @GammaMicrowave.

**Comment by Vishesh-Vijay** [comment]
Claim

**Comment by GammaMicrowave** [comment]
already finished  1 of them

**Comment by GammaMicrowave** [comment]
it is gonna  get pulled soon
the mentor is first pulling other request

**Comment by Manas2403** [comment]
In which repo @GammaMicrowave ?

**Comment by GammaMicrowave** [comment]
workwise

**Comment by Manas2403** [comment]
Assigned to @Vishesh-Vijay

**Comment by Vishesh-Vijay** [comment]
I'm really sorry @Manas2403 there's some urgent reason that i won't be able to complete this task. I would like this task to get reassigned to somebody else. Thank you and i apologize for the same.

**Comment by Manas2403** [comment]
Assigned to @GammaMicrowave
