### ISSUE TITLE
Code the Features Section

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#76]
For this task, you have to code the JSON Schema Validation feature section of the website. Design is provided in the figma link provided in README under heading HomeScreen Header. Desktop and mobile both designs are provided.

Steps to follow:
- Create a section named JSONSection in `components/sections/` and work there.
- Import the section in  `pages/home` .
- You can see your changes  on `http://localhost:3000/home.

---
Make the sure  section is responsive. No need to work on the  navbar and the hero section.

**Comment by GammaMicrowave** [comment]
Claim

**Comment by Manas2403** [comment]
You have an issue assigned to you

**Comment by GammaMicrowave** [comment]
💀 gib now then

**Comment by Manas2403** [comment]
No u have done wrong something wrong  in your previous task , solve that first @GammaMicrowave

**Comment by Manas2403** [comment]
Assigned to @GammaMicrowave

**Comment by Kali-Decoder** [comment]
claim
