### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#78]
For this task, you have to code the footer of the website. Design is provided in the figma link provided in README under heading Footer

Steps to follow:
- Create a section named Footer in `components/sections/` and work there.
- Import the section in  `pages/home` .
- You can see your changes  on `http://localhost:3000/home.

---
Make the sure footer is responsive. Both desktop and mobile designs are provided in the figma.

**Comment by GammaMicrowave** [comment]
claim

**Comment by GammaMicrowave** [comment]
bet you gonna say 3 issu

**Comment by Manas2403** [comment]
No you can only claim one issue in a repo at a time

**Comment by Shubhankit-Pandey** [comment]
Claim

**Comment by Manas2403** [comment]
Assigned to @Shubhankit-Pandey

**Comment by GammaMicrowave** [comment]
> No you can only claim one issue in a repo at a time

fric new reply

**Comment by Kali-Decoder** [comment]
Claim
