### ISSUE TITLE
Design the Home Page for the project SaveMyForm

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#8]
OPEN TO ALL.
NO need to claim this issue.
---
SaveMyForm is a project that is based on the idea of collecting form responses for other people.

Features:
- Secured(No Spam, JSON Schema Validation)
- Save upto 1000 form responses for 30 days
- Download form responses (CSV, PDF)
- Single File Upload Allowed 
- reCAPTCHA Support

These features should be displayed on the home screen and its upto you how to present it.

---
Reference Website: [MongoDB](https://www.mongodb.com/home)

Enter your github account and attach the figma link in the [designs.json](https://github.com/opencodeiiita/SaveMyForm-Frontend/blob/main/designs.json) file.

**Comment by Kali-Decoder** [comment]
Claim
