### ISSUE TITLE
Another Section 

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#82]
For this task, you have to code the Download your form responses feature section of the website. Design is provided in the figma link provided in README under heading HomeScreen Header. Desktop and mobile both designs are provided.

Steps to follow:
- Create a section named FormResponsesSection in `components/sections/` and work there.
- Import the section in  `pages/home` .
- You can see your changes  on `http://localhost:3000/home.

---
Make  sure the section is responsive.

**Comment by GammaMicrowave** [comment]
claim

**Comment by Manas2403** [comment]
No

**Comment by vishalola** [comment]
claim

**Comment by vishalola** [comment]
gamma hahahahah

**Comment by Manas2403** [comment]
Assigned to @vishalola

**Comment by GammaMicrowave** [comment]
F

**Comment by Manas2403** [comment]
Any doubts @vishalola ?

**Comment by vishalola** [comment]
@Manas2403 Nope, I'll be done till midnight
