### ISSUE TITLE
1000 responses

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#85]
For this task, you have to code the save upto 1000 responses feature section of the website. Design is provided in the figma link provided in README under heading HomeScreen Header. Desktop and mobile both designs are provided.

Steps to follow:
- Create a section named  SaveResponsesSection in `components/sections/` and work there.
- Import the section in  `pages/home` .
- You can see your changes  on `http://localhost:3000/home.

---
Make  sure the section is responsive.

**Comment by GammaMicrowave** [comment]
claim

**Comment by GammaMicrowave** [comment]
finally issuless

**Comment by Manas2403** [comment]
Assigned to @GammaMicrowave
