### ISSUE TITLE
Verification Page

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#86]
For this task, you have to code the verification page of the website. Design is provided in the figma link provided in README under heading Verificaton. 

Steps to follow:
-  Write your code [here](https://github.com/opencodeiiita/SaveMyForm-Frontend/blob/main/pages/verify/index.js)
- You can see your changes  on `http://localhost:3000/verify`.

---
Make  sure the page is responsive. For mobile design remove the left part with logo and name and just keep the right hand side of the desktop design.

**Comment by Shubhankit-Pandey** [comment]
claim

**Comment by Manas2403** [comment]
Assigned to @Shubhankit-Pandey
