### ISSUE TITLE
Single File Upload

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#89]
For this task, you have to code the save single file upload feature section of the website. Design is provided in the figma link provided in README under heading HomeScreen Header. Desktop and mobile both designs are provided.

Steps to follow:
- Create a section named  SingleFileSection in `components/sections/` and work there.
- Import the section in  `pages/home` .
- You can see your changes  on `http://localhost:3000/home.

---
Make  sure the section is responsive.

**Comment by GammaMicrowave** [comment]
claim

**Comment by vishalola** [comment]
claim

**Comment by vishalola** [comment]
hath jodta hu gamma... rehem karo bas ab🥺

**Comment by Manas2403** [comment]
Assigned to @GammaMicrowave

**Comment by GammaMicrowave** [comment]
@vishalola i c i clem
