### ISSUE TITLE
Create the Signup Page

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#9]
Create the signup page, just place, and style the components. You can add a suitable style to the text input fields. You can reference the attached image for the structure of the signup page, a vector will be placed on the left side in the future, for now you can use a coloured div instead of the vector.

Use [tailwind](https://tailwindcss.com/docs/installation) for styling, you can also use [antd components](https://ant.design/components/overview/) on this page.

---

You will have to write the code in this file: [pages > signup > index.js](https://github.com/opencodeiiita/SaveMyForm-Frontend/blob/main/pages/signup/index.js)

---

![Signup Page](https://imgur.com/GCucRWh.png)

---

Feel free to ask doubts on discord.

**Comment by Shubhankit-Pandey** [comment]
claim

**Comment by Manas2403** [comment]
Congratulations!. You have 48 hours for this task.
Happy Contributing!!

**Comment by shiva177** [comment]
claim

**Comment by Manas2403** [comment]
@shiva177  issue has already been claimed

**Comment by Phantom-Harsh** [comment]
Claim

**Comment by Manas2403** [comment]
@Phantom-Harsh  issue has already been claimed
