### ISSUE TITLE
Final Section 

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#92]
For this task, you have to code the reCAPTCHA support feature section of the website. Design is provided in the figma link provided in README under heading HomeScreen Header. Desktop and mobile both designs are provided.

Steps to follow:
- Create a section named  recaptchaSection in `components/sections/` and work there.
- Import the section in  `pages/home` .
- You can see your changes  on `http://localhost:3000/home`.

---
Make  sure the section is responsive.

**Comment by vishalola** [comment]
claim

**Comment by vishalola** [comment]
@GammaMicrowave wya braah

**Comment by Manas2403** [comment]
Assigned to @vishalola

**Comment by GammaMicrowave** [comment]
@vishalola mere pass already issu hai isliye baksh diya
