### ISSUE TITLE
Tabbed Settings 

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#94]
The settings page is already implemented [here](https://github.com/opencodeiiita/SaveMyForm-Frontend/blob/main/pages/settings/index.js).

For this task you have to create a  tabbed section as shown in figma file under heading Client Settings.

- When user clicks on password tab, the page should look like `Client Settings 2` as shown in figma file.
-  When user clicks on account tab, the page should look like `Client Settings` as shown in figma file.

Write your code [here](https://github.com/opencodeiiita/SaveMyForm-Frontend/blob/main/pages/settings/index.js).
Make sure page is responsive.

The `default` tab  to show is Account tab.

Also you have to make sure that user can know which tab is selected. It's upto you how to show which tab is selected. Either change color of selected tab or give it a background. It's all upto you.

**Comment by vishalola** [comment]
claim

**Comment by Manas2403** [comment]
Assigned to @vishalola

**Comment by GammaMicrowave** [comment]
firc

**Comment by vishalola** [comment]
@GammaMicrowave whatsapp dekh
