### ISSUE TITLE
Project Settings

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#96]
For this task, you have to create the project settings page. The page will look same to [this](https://github.com/opencodeiiita/SaveMyForm-Frontend/tree/main/pages/dashboard/project/newproject).

Write your code [here](https://github.com/opencodeiiita/SaveMyForm-Frontend/tree/main/pages/dashboard/project/%5Bid%5D/settings).

Steps to follow:
- Change the Submit button to Save.

**Comment by GammaMicrowave** [comment]
claim

**Comment by JahnaviGadde** [comment]
claim

**Comment by iamatifmoin** [comment]
claim

**Comment by Manas2403** [comment]
Assigned to @JahnaviGadde

**Comment by Shubhankit-Pandey** [comment]
claim

**Comment by Manas2403** [comment]
Assigned to @Shubhankit-Pandey
