### ISSUE TITLE
One Last Time

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/SaveMyForm-Frontend#97]
The home page is ready for the project SaveMyForm.  For this task you have to give final touches to the page. The page should be completely responsive on every device,  increase or decrease the font size,  increase padding, change icons ,etc. 

Show your CSS skills and make the page as good as possible. The desktop and mobile designs are provided in figma file.  You have to make sure it looks almost same to it else your PR will not be merged.

**Comment by GammaMicrowave** [comment]
claim

**Comment by Manas2403** [comment]
Assigned to @GammaMicrowave

**Comment by iamatifmoin** [comment]
Claim

**Comment by Manas2403** [comment]
Assigned to @iamatifmoin

**Comment by Manas2403** [comment]
@iamatifmoin  you have 48hrs to complete the task

**Comment by iamatifmoin** [comment]
@Manas2403 
I get a blank white screen when I run 'npm run dev'. 
How do I fix this?

The terminal looks like this:
![Capture](https://user-images.githubusercontent.com/97212195/210081203-35da5e78-fc37-433d-954a-f5ba3b25eb01.PNG)

**Comment by Manas2403** [comment]
Go to localhost:3000/home.

**Comment by iamatifmoin** [comment]
@Manas2403 
Thanks!
PR: #100

**Comment by Manas2403** [comment]
updates @iamatifmoin ?

**Comment by TheDivineAurora** [comment]
claim

**Comment by Manas2403** [comment]
Updates @TheDivineAurora
